# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-10.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-10.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michaelguarino/ShareCameraQt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michaelguarino/ShareCameraQt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-10.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-10.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelguarino/ShareCameraQt/CMakeFiles /Users/michaelguarino/ShareCameraQt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelguarino/ShareCameraQt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ShareCameraQt

# Build rule for target.
ShareCameraQt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ShareCameraQt
.PHONY : ShareCameraQt

# fast build rule for target.
ShareCameraQt/fast:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/build
.PHONY : ShareCameraQt/fast

ShareCameraQt.o: ShareCameraQt.cxx.o
.PHONY : ShareCameraQt.o

# target to build an object file
ShareCameraQt.cxx.o:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/ShareCameraQt.cxx.o
.PHONY : ShareCameraQt.cxx.o

ShareCameraQt.i: ShareCameraQt.cxx.i
.PHONY : ShareCameraQt.i

# target to preprocess a source file
ShareCameraQt.cxx.i:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/ShareCameraQt.cxx.i
.PHONY : ShareCameraQt.cxx.i

ShareCameraQt.s: ShareCameraQt.cxx.s
.PHONY : ShareCameraQt.s

# target to generate assembly for a file
ShareCameraQt.cxx.s:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/ShareCameraQt.cxx.s
.PHONY : ShareCameraQt.cxx.s

ShareCameraQtDriver.o: ShareCameraQtDriver.cxx.o
.PHONY : ShareCameraQtDriver.o

# target to build an object file
ShareCameraQtDriver.cxx.o:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/ShareCameraQtDriver.cxx.o
.PHONY : ShareCameraQtDriver.cxx.o

ShareCameraQtDriver.i: ShareCameraQtDriver.cxx.i
.PHONY : ShareCameraQtDriver.i

# target to preprocess a source file
ShareCameraQtDriver.cxx.i:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/ShareCameraQtDriver.cxx.i
.PHONY : ShareCameraQtDriver.cxx.i

ShareCameraQtDriver.s: ShareCameraQtDriver.cxx.s
.PHONY : ShareCameraQtDriver.s

# target to generate assembly for a file
ShareCameraQtDriver.cxx.s:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/ShareCameraQtDriver.cxx.s
.PHONY : ShareCameraQtDriver.cxx.s

moc_ShareCameraQt.o: moc_ShareCameraQt.cxx.o
.PHONY : moc_ShareCameraQt.o

# target to build an object file
moc_ShareCameraQt.cxx.o:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/moc_ShareCameraQt.cxx.o
.PHONY : moc_ShareCameraQt.cxx.o

moc_ShareCameraQt.i: moc_ShareCameraQt.cxx.i
.PHONY : moc_ShareCameraQt.i

# target to preprocess a source file
moc_ShareCameraQt.cxx.i:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/moc_ShareCameraQt.cxx.i
.PHONY : moc_ShareCameraQt.cxx.i

moc_ShareCameraQt.s: moc_ShareCameraQt.cxx.s
.PHONY : moc_ShareCameraQt.s

# target to generate assembly for a file
moc_ShareCameraQt.cxx.s:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/moc_ShareCameraQt.cxx.s
.PHONY : moc_ShareCameraQt.cxx.s

moc_ui_ShareCameraQt.o: moc_ui_ShareCameraQt.cxx.o
.PHONY : moc_ui_ShareCameraQt.o

# target to build an object file
moc_ui_ShareCameraQt.cxx.o:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/moc_ui_ShareCameraQt.cxx.o
.PHONY : moc_ui_ShareCameraQt.cxx.o

moc_ui_ShareCameraQt.i: moc_ui_ShareCameraQt.cxx.i
.PHONY : moc_ui_ShareCameraQt.i

# target to preprocess a source file
moc_ui_ShareCameraQt.cxx.i:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/moc_ui_ShareCameraQt.cxx.i
.PHONY : moc_ui_ShareCameraQt.cxx.i

moc_ui_ShareCameraQt.s: moc_ui_ShareCameraQt.cxx.s
.PHONY : moc_ui_ShareCameraQt.s

# target to generate assembly for a file
moc_ui_ShareCameraQt.cxx.s:
	$(MAKE) -f CMakeFiles/ShareCameraQt.dir/build.make CMakeFiles/ShareCameraQt.dir/moc_ui_ShareCameraQt.cxx.s
.PHONY : moc_ui_ShareCameraQt.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ShareCameraQt"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ShareCameraQt.o"
	@echo "... ShareCameraQt.i"
	@echo "... ShareCameraQt.s"
	@echo "... ShareCameraQtDriver.o"
	@echo "... ShareCameraQtDriver.i"
	@echo "... ShareCameraQtDriver.s"
	@echo "... moc_ShareCameraQt.o"
	@echo "... moc_ShareCameraQt.i"
	@echo "... moc_ShareCameraQt.s"
	@echo "... moc_ui_ShareCameraQt.o"
	@echo "... moc_ui_ShareCameraQt.i"
	@echo "... moc_ui_ShareCameraQt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

